import {initialState,legalMoves,flipsFor,play,score,chooseMove,restoreGame,GUAVA,GRAPE} from './engine.js';
const $=s=>document.querySelector(s),NAME={1:'芭乐','-1':'青提'},SAVE='fruit-reversi-v1',SESSION='reversi-room-v2';
let state=initialState(),mode='local',history=[],entry='create',page='home',auth=null,room=null,connected=false,pending=false,locked=false,epoch=0,aiTimer,pollTimer,animationTimer,toastTimer,resultStamp='',focusIndex=19;
try{auth=JSON.parse(sessionStorage.getItem(SESSION));if(!auth||typeof auth.code!=='string'||typeof auth.token!=='string')auth=null;}catch{}
function notify(text){$('#toast').textContent=text;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,3000);}
function coin(side,extra=''){const n=document.createElement('span');n.className=`coin ${side===GUAVA?'guava':'grape'}-coin ${extra}`;const im=document.createElement('img');im.src=`assets/${side===GUAVA?'guava-v2':'grape'}.jpg`;im.alt='';im.draggable=false;n.append(im);return n;}
function coord(i){return 'ABCDEFGH'[i%8]+(Math.floor(i/8)+1);}
for(const [position,values]of [['top',[...'ABCDEFGH']],['left',[1,2,3,4,5,6,7,8]]])for(const value of values){const n=document.createElement('span');n.textContent=value;$('.coordinates.'+position).append(n);}
function route(next){page=next;for(const id of ['home','waiting','play-page'])$('#'+id).hidden=id!==next;window.scrollTo({top:0});}
function preserveAuth(){try{if(auth)sessionStorage.setItem(SESSION,JSON.stringify(auth));else sessionStorage.removeItem(SESSION);}catch{notify('浏览器无法保存身份，请保持当前页面打开');}$('#resume-room').hidden=!auth;}
function saveLocal(){try{localStorage.setItem(SAVE,JSON.stringify({version:1,mode,history}));}catch{notify('浏览器无法保存棋局，本局仍可继续');}}
async function api(endpoint,data,identity=auth){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),6500);try{const res=await fetch(new URL('api/'+endpoint,new URL('.',location.href)),{method:data===undefined?'GET':'POST',headers:{...(data===undefined?{}:{'Content-Type':'application/json'}),...(identity?{Authorization:'Bearer '+identity.token}:{})},body:data===undefined?undefined:JSON.stringify(data),signal:controller.signal,cache:'no-store'});const out=await res.json();if(!res.ok){const e=new Error(out.error||'操作没有完成');e.status=res.status;throw e;}return out;}catch(e){if(e.name==='AbortError')throw Error('连接超时，请检查网络后重试');throw e;}finally{clearTimeout(timeout);}}
function setEntry(next){entry=next;$('#create-tab').setAttribute('aria-selected',String(next==='create'));$('#join-tab').setAttribute('aria-selected',String(next==='join'));$('#room-field').hidden=next!=='join';$('#room-code').required=next==='join';$('#create-description').hidden=next==='join';$('#entry-title').textContent=next==='join'?'和朋友会合':'开始一局';$('#entry-submit').textContent=next==='join'?'加入房间':'创建房间';$('#entry-error').textContent='';}
$('#create-tab').onclick=()=>setEntry('create');$('#join-tab').onclick=()=>setEntry('join');
$('#entry-form').onsubmit=async e=>{e.preventDefault();if(pending)return;pending=true;$('#entry-submit').disabled=true;$('#entry-error').textContent='';try{const nickname=$('#nickname').value.trim(),code=$('#room-code').value.trim().toUpperCase();const out=await api(entry==='create'?'rooms':`rooms/${encodeURIComponent(code)}/join`,{nickname},null);auth={code:out.room.code,token:out.token};preserveAuth();enterOnline(out.room);}catch(e){$('#entry-error').textContent=e.message;}finally{pending=false;$('#entry-submit').disabled=false;}};
function enterOnline(snapshot){epoch++;clearTimeout(aiTimer);clearTimeout(pollTimer);clearTimeout(animationTimer);locked=false;mode='online';room=null;resultStamp='';connected=true;applyRoom(snapshot);poll();}
function applyRoom(next){if(!auth||next.code!==auth.code||room&&next.version<room.version)return;const changed=!room||next.version!==room.version,wasConnected=connected;const oldGame=room?.game,oldSide=room?.side;room=next;connected=true;if(!changed&&wasConnected&&page!=='home')return;if(oldSide&&oldSide!==room.side)notify(room.status==='finished'?'已交换下一局先后手':'先后手已交换');
 if(next.status==='waiting'){routeIfNeeded('waiting');renderWaiting();return;}
 if(!next.game)return;state=next.game;routeIfNeeded('play-page');
 if(!state.over){resultStamp='';if($('#modal').open&&$('#modal').dataset.kind==='result')$('#modal').close();}
 const animate=changed&&oldGame&&state.moves===oldGame.moves+1;
 if(animate){locked=true;clearTimeout(animationTimer);animationTimer=setTimeout(()=>{locked=false;render();maybeResult();},360);}
 render(animate);if(!animate)maybeResult();
}
function routeIfNeeded(next){if(page!==next)route(next);}
async function poll(){clearTimeout(pollTimer);const generation=epoch,identity=auth;if(mode!=='online'||!identity||page==='home')return;try{const out=await api('rooms/'+identity.code,undefined,identity);if(generation!==epoch)return;applyRoom(out.room);}catch(e){if(generation!==epoch)return;connected=false;if(e.status===401||e.status===404){auth=null;preserveAuth();goHome();notify(e.message);return;}if(page==='waiting'){renderWaiting();$('#waiting-status').textContent='正在重新连接…';}else render();}finally{if(generation===epoch&&auth&&mode==='online'&&page!=='home')pollTimer=setTimeout(poll,document.hidden?2800:1200);}}
async function action(type,index){if(pending||!connected||!auth||!room)return;const generation=epoch,identity=auth,payload={type,index,expectedVersion:room.version,requestId:crypto.randomUUID()};pending=true;renderIfPlaying();if(page==='waiting')renderWaiting();try{let out;try{out=await api(`rooms/${identity.code}/action`,payload,identity);}catch(e){if(e.status)throw e;out=await api(`rooms/${identity.code}/action`,payload,identity);}if(generation===epoch)applyRoom(out.room);}catch(e){if(generation===epoch){notify(e.message);poll();}}finally{if(generation===epoch){pending=false;renderIfPlaying();if(page==='waiting')renderWaiting();}}}
function renderWaiting(){$('#waiting-code').textContent=room.code;$('#waiting-members').replaceChildren();for(const side of[GUAVA,GRAPE]){const member=room.members.find(m=>m.side===side),row=document.createElement('div');row.className='member-row';row.append(coin(side));const label=document.createElement('div');label.textContent=member?member.name:'等待好友加入…';const note=document.createElement('small');note.textContent=member?(member.id===room.hostId?'房主 · ':'')+(side===GUAVA?'先手':'后手'):'把房间号分享给朋友';label.append(note);row.append(label);$('#waiting-members').append(row);}const isHost=room.selfId===room.hostId,ready=room.members.length===2;$('#start').disabled=!connected||pending||!isHost||!ready||!!room.swapRequest;$('#start').textContent=!connected?'正在重新连接…':!ready?'等待好友加入':isHost?'开始对局':'等待房主开始';$('#waiting-status').textContent=room.swapRequest?(room.swapRequest===room.selfId?'等待好友确认交换…':'好友希望交换先后手，请确认。'):ready?'两位玩家已到齐，可以开始了。':'好友加入后，由房主开始对局。';updateSwapUI();}
function renderIfPlaying(){if(page==='play-page')render();}
function render(animate=false){const s=score(state.board),online=mode==='online',human=!state.over&&!locked&&!pending&&(online?connected&&room?.side===state.turn:!(mode==='ai'&&state.turn===GRAPE));const options=legalMoves(state.board,state.turn);$('#guava-score').textContent=s.guava;$('#grape-score').textContent=s.grape;
 for(const side of[GUAVA,GRAPE]){const key=side===GUAVA?'guava':'grape',member=online?(state.over?room.gameMembers||room.members:room.members).find(m=>m.side===side):null;$('#'+key+'-name').textContent=member?member.name:NAME[side];$('#'+key+'-note').textContent=online?(member?.id===room.selfId?'你 · ':'')+(side===GUAVA?'先手':'后手'):mode==='ai'?(side===GUAVA?'你 · 先手':'电脑'):(side===GUAVA?'先手':'后手');$('#player-'+key).classList.toggle('active',!state.over&&state.turn===side);}
 $('#mode-label').textContent=online?'好友对局':mode==='ai'?'人机练习':'同屏双人';$('#turn').textContent=state.over?'这一局，收获满满':online?(state.turn===room.side?'轮到你落子':'等待朋友落子'):`轮到${NAME[state.turn]}落子`;
 $('#notice').textContent=state.over?(online&&room.reason==='left'?'对方已离开，本局结束。':'本局结束，可以再来一局。'):state.passed?`${NAME[state.passed]}无棋可下，自动跳过`:(mode==='ai'&&state.turn===GRAPE?'青提正在思考下一步…':'选择圆点，翻转对手的棋子。');
 $('#connection').textContent=online?`房间 ${room.code} · ${connected?'已连接':'连接中断，正在重试…'}`:'自动保存 · 随时回来继续';$('#resign').hidden=!online||state.over;$('#resign').disabled=pending||!connected;$('#restart').hidden=online&&!state.over;$('#restart').textContent=online?'邀请再来一局':'重新开始';$('#restart').disabled=online&&(pending||!connected||room.members.some(m=>m.left)||room.votes.includes(room.selfId)||!!room.swapRequest);if(online&&room.votes.includes(room.selfId))$('#restart').textContent='等待朋友同意';$('#leave-game').textContent=online?'离开对局':'返回首页';
 const board=$('#board'),focused=board.contains(document.activeElement);board.dataset.turn=state.turn;board.replaceChildren();state.board.forEach((value,index)=>{const b=document.createElement('button');b.className='cell';b.type='button';b.setAttribute('role','gridcell');b.dataset.index=index;b.tabIndex=index===focusIndex?0:-1;const legal=human&&options.includes(index);b.classList.toggle('legal',legal);b.classList.toggle('last',state.last===index);b.setAttribute('aria-disabled',String(!legal));b.setAttribute('aria-label',`${coord(index)}，${value?NAME[value]:'空格'}${legal?'，可落子':''}`);if(value)b.append(coin(value,animate&&state.last===index?'planted':animate&&state.flipped?.includes(index)?'flipping':''));b.onclick=()=>move(index);b.onpointerenter=e=>{if(!legal||e.pointerType==='touch')return;flipsFor(state.board,index,state.turn).forEach(i=>board.children[i].classList.add('preview-flip'));};b.onpointerleave=()=>board.querySelectorAll('.preview-flip').forEach(n=>n.classList.remove('preview-flip'));b.onkeydown=e=>{const d={ArrowLeft:-1,ArrowRight:1,ArrowUp:-8,ArrowDown:8}[e.key];if(d===undefined)return;e.preventDefault();focusIndex=Math.min(63,Math.max(0,index+d));b.tabIndex=-1;board.children[focusIndex].tabIndex=0;board.children[focusIndex].focus();};board.append(b);});if(focused)board.children[focusIndex].focus();updateSwapUI();}
function move(index,computer=false){if(page!=='play-page'||locked||pending||state.over||$('#modal').open)return;if(mode==='online'){if(!connected||state.turn!==room.side)return;if(!flipsFor(state.board,index,state.turn).length)return notify('请选择带圆点的空格');action('move',index);return;}if(mode==='ai'&&state.turn===GRAPE&&!computer)return;const next=play(state,index);if(!next)return notify('请选择带圆点的空格');state=next;history.push(index);focusIndex=index;saveLocal();locked=true;render(true);const generation=epoch;clearTimeout(animationTimer);animationTimer=setTimeout(()=>{if(generation!==epoch)return;locked=false;render();maybeResult();scheduleAI();},360);}
function scheduleAI(){clearTimeout(aiTimer);if(mode!=='ai'||state.over||state.turn!==GRAPE||page!=='play-page'||$('#modal').open)return;const generation=epoch;aiTimer=setTimeout(()=>{if(generation===epoch)move(chooseMove(state,3),true);},420);}
function startLocal(nextMode){epoch++;clearTimeout(pollTimer);clearTimeout(aiTimer);clearTimeout(animationTimer);mode=nextMode;locked=false;pending=false;state=initialState();history=[];resultStamp='';try{const saved=restoreGame(JSON.parse(localStorage.getItem(SAVE)));if(saved&&saved.mode===nextMode&&!saved.state.over){state=saved.state;history=saved.history;}}catch{}route('play-page');render();scheduleAI();}
function resetLocal(){epoch++;clearTimeout(aiTimer);clearTimeout(animationTimer);locked=false;state=initialState();history=[];resultStamp='';saveLocal();render();}
function modal(html,kind='normal'){clearTimeout(aiTimer);$('#modal').dataset.kind=kind;$('#modal-content').innerHTML=html;if(!$('#modal').open)$('#modal').showModal();}
$('#modal').addEventListener('close',()=>{renderIfPlaying();if(state.over)maybeResult();else scheduleAI();});
function maybeResult(){if(page!=='play-page'||!state.over||locked||$('#modal').open)return;const stamp=mode==='online'?room.code+':'+room.game.moves+':'+room.reason:mode+':'+history.length;if(resultStamp===stamp)return;resultStamp=stamp;const s=score(state.board),winner=mode==='online'?room.winner:Math.sign(s.guava-s.grape);modal(`<div class="result"><p class="eyebrow">这一局，感谢有你</p><div id="result-art" class="result-art"></div><h2 id="modal-title">${winner?`${NAME[winner]}获胜`:'平分秋色'}</h2><p class="dialog-intro">${mode==='online'&&room.reason==='left'?'对方已离开，本局结束。':mode==='online'&&room.reason==='resigned'?'一方认输，本局结束。':'每一次翻转，都有新的可能。'}</p><p class="result-score">${s.guava} : ${s.grape}</p><div class="dialog-actions"><button class="primary" id="result-again">${mode==='online'?'邀请再来一局':'再来一局'}</button>${mode==='online'?'<p id="result-next" class="dialog-intro"></p><button class="secondary" id="result-swap">交换先后手</button>':''}<button class="secondary" id="result-board">看看棋盘</button></div></div>`,'result');for(const side of(winner?[winner]:[GUAVA,GRAPE]))$('#result-art').append(coin(side));$('#result-board').onclick=()=>$('#modal').close();$('#result-again').disabled=mode==='online'&&room.members.some(m=>m.left);$('#result-again').onclick=()=>{$('#modal').close();if(mode==='online')action('replay');else resetLocal();};if($('#result-swap'))$('#result-swap').onclick=swapDialog;updateSwapUI();}
$('#restart').onclick=()=>{if(mode==='online'){action('replay');return;}if(!state.moves||state.over){resetLocal();return;}modal('<h2 id="modal-title">重新开始这一局？</h2><p class="dialog-intro">当前棋局会结束，双方重新从两枚棋子开始。</p><div class="dialog-actions"><button class="primary" id="confirm-reset">开始新局</button><button class="secondary" id="keep-game">继续本局</button></div>');$('#confirm-reset').onclick=()=>{resetLocal();$('#modal').close();};$('#keep-game').onclick=()=>$('#modal').close();};
function goHome(){epoch++;clearTimeout(pollTimer);clearTimeout(aiTimer);clearTimeout(animationTimer);locked=false;pending=false;route('home');preserveAuth();}
function requestExit(){if(page==='home')return;if(mode!=='online'){goHome();return;}modal('<h2 id="modal-title">离开这个房间？</h2><p class="dialog-intro">对局中离开会结束本局。若只想暂时切换页面，可以直接关闭此弹窗。</p><div class="dialog-actions"><button class="primary" id="confirm-leave">离开房间</button><button class="secondary" id="stay">继续留下</button></div>');$('#stay').onclick=()=>$('#modal').close();$('#confirm-leave').onclick=async()=>{const b=$('#confirm-leave');b.disabled=true;try{await api(`rooms/${auth.code}/leave`,{});auth=null;room=null;preserveAuth();goHome();$('#modal').close();}catch(e){if(e.status===401||e.status===404){auth=null;room=null;goHome();$('#modal').close();}else{notify(e.message);b.disabled=false;}}};}
$('#brand').onclick=requestExit;$('#leave-wait').onclick=requestExit;$('#leave-game').onclick=requestExit;$('#start').onclick=()=>action('start');$('#local').onclick=()=>startLocal('local');$('#ai').onclick=()=>startLocal('ai');
$('#resume-room').onclick=async()=>{if(!auth)return;try{const out=await api('rooms/'+auth.code);enterOnline(out.room);}catch(e){notify(e.message);if(e.status===401||e.status===404){auth=null;preserveAuth();}}};
async function invite(){if(!room)return;const url=new URL('.',location.href);url.searchParams.set('room',room.code);try{await navigator.clipboard.writeText(url.href);notify('邀请链接已复制');}catch{modal('<h2 id="modal-title">邀请朋友</h2><p class="dialog-intro">把这个房间号告诉朋友：</p><p id="invite-code" class="result-score"></p>');$('#invite-code').textContent=room.code;}}
$('#copy-wait').onclick=invite;$('#resign').onclick=()=>{modal('<h2 id="modal-title">确认认输？</h2><p class="dialog-intro">认输后，本局将结束，对方获胜。你们仍可以留在房间再来一局。</p><div class="dialog-actions"><button class="primary" id="confirm-resign">确认认输</button><button class="secondary" id="keep-playing">继续下棋</button></div>');$('#keep-playing').onclick=()=>$('#modal').close();$('#confirm-resign').onclick=()=>{$('#modal').close();action('resign');};};
$('#rules').onclick=()=>{modal('<h2 id="modal-title">黑白棋怎么玩</h2><ol class="rules-list"><li>芭乐先手，青提后手。棋子落在格子里。</li><li>横、竖或斜线夹住连续的对手棋子，就把它们全部翻转。每步至少翻转一枚。</li><li>没有合法落点时自动跳过，不能主动跳过有棋可下的回合。</li><li>双方均无棋可下时结束，棋子多者获胜，同数和局。</li></ol><p class="dialog-intro">在线由房主开始；再来一局需双方同意。刷新后可从首页回到房间。键盘方向键选择，回车或空格落子。</p><div class="dialog-actions"><button class="primary" id="understood">知道了</button></div>');$('#understood').onclick=()=>$('#modal').close();};

function updateSwapUI(){
 const online=mode==='online'&&room,available=online&&['waiting','finished'].includes(room.status)&&!room.members.some(m=>m.left);
 $('.game-actions').classList.toggle('has-swap',!!available&&room.status==='finished');
 const request=room?.swapRequest,own=request===room?.selfId;
 const label=request?(own?'取消交换申请':'回应交换申请'):'交换先后手';
 for(const id of ['swap-wait','swap-game','result-swap']){const b=$('#'+id);if(!b)continue;b.hidden=!available||(id==='swap-game'&&room.status!=='finished');b.textContent=label;b.disabled=pending||!connected;}
 const next=$('#result-next');if(next&&online)next.textContent=request?(own?'等待好友确认交换…':'好友希望交换先后手'):`下一局：你${room.side===GUAVA?'先手':'后手'} · 好友${room.side===GUAVA?'后手':'先手'}`;
 if(online&&room.status==='finished')$('#connection').textContent=`房间 ${room.code} · 下一局你${room.side===GUAVA?'先手':'后手'}${request?' · 交换申请待确认':''}`;
 const again=$('#result-again');if(again&&online){again.disabled=pending||!connected||!!request||room.members.some(m=>m.left)||room.votes.includes(room.selfId);if(room.votes.includes(room.selfId))again.textContent='等待朋友同意';}
}
function swapDialog(){
 if(mode!=='online'||!room||pending||!connected)return;
 if(room.swapRequest===room.selfId){action('swap-cancel');return;}
 const incoming=!!room.swapRequest,solo=room.members.length===1;
 modal(`<h2 id="modal-title">${incoming?'好友想交换先后手':'交换先后手？'}</h2><p class="dialog-intro">${incoming?'同意后':'交换后'}，你将改为${room.side===GUAVA?'后手':'先手'}。${room.status==='finished'?'只影响下一局，本局结果保持不变。':solo?'好友加入后会使用另一方。':'需要双方同意后才会生效。'}</p><div class="dialog-actions"><button id="swap-confirm" class="primary">${incoming?'同意交换':solo?'确认交换':'向好友发起交换'}</button><button id="swap-decline" class="secondary">${incoming?'保持不变':'取消'}</button></div>`,'swap');
 $('#swap-confirm').onclick=()=>{$('#modal').close();action(incoming?'swap-accept':'swap-request');};
 $('#swap-decline').onclick=()=>{$('#modal').close();if(incoming)action('swap-decline');};
}
$('#swap-wait').onclick=swapDialog;$('#swap-game').onclick=swapDialog;

const code=new URL(location.href).searchParams.get('room');if(code&&/^[A-Za-z0-9]{6}$/.test(code)){setEntry('join');$('#room-code').value=code.toUpperCase();}
preserveAuth();route('home');
